### PR TITLE
Two more

### PR DESCRIPTION
**Pull request by henning-schild**
The second one should become invalid once i invalidate the certificate i used, the first one should stay valid.

The way it works is that the second one is from the future, where the certificate will be invalidated.

### CODE REVIEW

**Comment by bufferoverflow** [comment]
@henning-schild Could you please push directly to the branch `feat/smime-signed-commits`
over here: https://gitlab.com/siemens/gitlab-test/ ? This here is just a mirror and master is managed by gitlab.

**Comment by henning-schild** [comment]
Sure. Funny that github claims "The email in this signature doesn’t match the committer email. "

I cant find the mistake ...

**Comment by henning-schild** [comment]
ERROR: Permission to siemens/gitlab-test.git denied to henning-schild.
fatal: Could not read from remote repository.

**Comment by bufferoverflow** [comment]
@henning-schild Jetzt söttis go, han di maintainer gmacht uf https://gitlab.com/siemens/gitlab-test , bitte in `feat/smime-signed-commits` zwig drucka

**Comment by gernot-h** [comment]
So "drucka" is the official Siemens DevOps term for "pushing"? Love it!

**Pull request closed without merging**
